repos:
  - repo: local
    hooks:
      - id: pylint
        name: PyLint
        entry: uv run pylint backend/
        language: system
        pass_filenames: false
        files: ^backend/.*\.py$

      - id: mypy
        name: Mypy
        entry: uv run mypy backend/
        language: system
        pass_filenames: false
        files: ^backend/.*\.py$

      - id: pyright
        name: Pyright
        entry: uv run pyright backend/
        language: system
        pass_filenames: false
        files: ^backend/.*\.py$

      - id: pytest
        name: Pytest
        entry: uv run pytest backend/
        language: system
        pass_filenames: false
        files: ^backend/.*\.py$

      - id: eslint
        name: ESLint
        entry: npm run lint
        language: system
        pass_filenames: false
        files: ^(public/js/.*\.js|e2e/.*\.js)$

      - id: phpcs
        name: PHP CodeSniffer
        entry: composer run lint
        language: system
        pass_filenames: false
        files: ^backend/.*\.php$

      - id: phpunit
        name: PHPUnit
        entry: composer run test
        language: system
        pass_filenames: false
        files: ^backend/.*\.php$
