[mypy]

# Geopandas does not ship PEP 561-compliant type markers or official type stubs
[mypy-geopandas.*]
ignore_missing_imports = True

# Shapely does not ship PEP 561-compliant type markers or official type stubs
[mypy-shapely.*]
ignore_missing_imports = True
