<?php

declare(strict_types=1);

namespace App\Tests;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\Attributes\CoversClass;
use App\Services\ExportService;
use DOMDocument;

/**
 * GpxSchemaTest
 *
 * Verifies that the GPX files generated by the ExportService strictly conform
 * to the official TopoGrafix GPX 1.1 XML Schema Definition (XSD).
 */
#[CoversClass(ExportService::class)]
class GpxSchemaTest extends TestCase
{
    private ExportService $exportService;

    protected function setUp(): void
    {
        $this->exportService = new ExportService();
    }

    /**
     * Asserts that a populated GPX document cleanly passes XSD validation.
     */
    #[Test]
    public function generatedGpxStrictlyAdheresToSchemaDefinition()
    {
        $points = [
            ['id' => 'GD001-AAAA', 'lat' => 45.0, 'lon' => -70.0],
            ['id' => 'GD001-BBBB', 'lat' => 46.0, 'lon' => -71.0],
        ];

        $xml = $this->exportService->generateXml($points, 'gpx');

        $dom = new DOMDocument();
        // Prevent libxml from throwing native warnings on stdout during test runs
        libxml_use_internal_errors(true);

        $dom->loadXML($xml);

        // We use a locally cached fixture of the XSD to prevent brittle tests
        // that would fail if topografix.com has network downtime.
        $xsdPath = __DIR__ . '/fixtures/gpx.xsd';

        // Assert the schema exists
        $this->assertFileExists($xsdPath, 'The local GPX XSD fixture must exist.');

        $isValid = $dom->schemaValidate($xsdPath);

        // If it fails, capture the exact errors for the PHPUnit output
        $errors = '';
        if (!$isValid) {
            foreach (libxml_get_errors() as $error) {
                $errors .= trim($error->message) . "\n";
            }
        }
        libxml_clear_errors();

        $this->assertTrue($isValid, "The generated GPX failed XSD validation. Errors:\n" . $errors);
    }
}
