<?php

declare(strict_types=1);

namespace App\Tests;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\Attributes\CoversClass;
use App\Services\ExportService;
use DOMDocument;

/**
 * LocSchemaTest
 *
 * Verifies that the LOC files generated by the ExportService correctly conform
 * to a custom XSD derived from Groundspeak's legacy Geocaching LOC format.
 */
#[CoversClass(ExportService::class)]
class LocSchemaTest extends TestCase
{
    private ExportService $exportService;

    protected function setUp(): void
    {
        $this->exportService = new ExportService();
    }

    /**
     * Asserts that a populated LOC document cleanly passes XSD validation.
     */
    #[Test]
    public function generatedLocStrictlyAdheresToCustomSchemaDefinition()
    {
        $points = [
            ['id' => 'GD001-AAAA', 'lat' => 45.0, 'lon' => -70.0],
            ['id' => 'GD001-BBBB', 'lat' => 46.0, 'lon' => -71.0],
        ];

        $xml = $this->exportService->generateXml($points, 'loc');

        $dom = new DOMDocument();
        // Prevent libxml from throwing native warnings on stdout during test runs
        libxml_use_internal_errors(true);

        $dom->loadXML($xml);

        $xsdPath = __DIR__ . '/fixtures/loc.xsd';

        // Assert the schema exists
        $this->assertFileExists($xsdPath, 'The local LOC XSD fixture must exist.');

        $isValid = $dom->schemaValidate($xsdPath);

        // If it fails, capture the exact errors for the PHPUnit output
        $errors = '';
        if (!$isValid) {
            foreach (libxml_get_errors() as $error) {
                $errors .= trim($error->message) . "\n";
            }
        }
        libxml_clear_errors();

        $this->assertTrue($isValid, "The generated LOC failed XSD validation. Errors:\n" . $errors);
    }
}
