name: JS Lint Checks

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - 'js/**/*.js'
      - 'e2e/**/*.js'
      - 'eslint.config.mjs'
      - 'package.json'
      - '.github/workflows/ci-js-lint.yml'
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - 'js/**/*.js'
      - 'e2e/**/*.js'
      - 'eslint.config.mjs'
      - 'package.json'
      - '.github/workflows/ci-js-lint.yml'
  workflow_dispatch:

jobs:
  eslint:
    name: ESLint Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
