name: Python Tests

permissions:
  contents: read

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/ci-python.yml'
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/ci-python.yml'
  workflow_dispatch:

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Pytest
        run: PYTHONPATH=. pytest backend/tests/
